"""Build a DuckDB database from processed Parquet files."""

from pathlib import Path

import duckdb


# Directory containing processed datasets generated by the preprocessing pipeline
PROCESSED_DIR = Path("data/processed")

# Local DuckDB database file used for analytical queries
DB_PATH = Path("data/energy.duckdb")


def build_duckdb() -> None:
    """Create DuckDB tables from processed Parquet datasets."""

    # Open a connection to the DuckDB database.
    # The database file is created automatically if it does not exist.
    con = duckdb.connect(str(DB_PATH))

    # Create one database table for each available data resolution.
    # This allows efficient querying at different forecasting horizons:
    # minute-level, hourly aggregated, and daily aggregated data.
    for table in ["minute", "hourly", "daily"]:

        # Locate the corresponding Parquet file
        parquet_path = PROCESSED_DIR / f"{table}.parquet"

        # Remove the existing table to ensure the database
        # always reflects the latest processed data.
        con.execute(f"DROP TABLE IF EXISTS {table}")

        # Create a DuckDB table directly from the Parquet file.
        # DuckDB can efficiently query Parquet without additional conversion steps.
        con.execute(
            f"""
            CREATE TABLE {table} AS
            SELECT *
            FROM read_parquet('{parquet_path}')
            """
        )

        # Verify that data was successfully loaded
        count = con.execute(
            f"SELECT COUNT(*) FROM {table}"
        ).fetchone()[0]

        print(f"Loaded table '{table}': {count:,} rows")

    # Close the connection to safely write changes to disk
    con.close()

    print(f"DuckDB database ready at {DB_PATH}")


if __name__ == "__main__":
    build_duckdb()